FROM balenalib/raspberrypi3-alpine-golang:latest-latest-build AS build

RUN apk add --no-cache ca-certificates git

WORKDIR /src

COPY ./go.mod ./go.sum ./
RUN go mod download

COPY ./app ./

RUN go build

CMD ./app